import json
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from leadflow_common import parse_leadflow, validate_config, run_training, run_scoring
import dsl_processor as dslproc

st.set_page_config(page_title="LeadFlowML Studio", layout="wide")

DEFAULT_GRAMMAR = ROOT / "dsl" / "leadflow.tx"
DEFAULT_DSL = ROOT / "workflows" / "lead_qualification.leadflow"
DEFAULT_TRAIN = ROOT / "data" / "train_sales_cases.csv"
DEFAULT_SCORE = ROOT / "data" / "new_sales_cases.csv"


def _write_uploaded(uploaded_file, destination: Path):
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(uploaded_file.getvalue())


def _render_metric_cards(report: dict):
    metrics = report.get("metrics", {})
    cols = st.columns(5)
    ordered = [("accuracy", "Accuracy"), ("precision", "Precision"), ("recall", "Recall"), ("f1", "F1"), ("roc_auc", "ROC AUC")]
    for col, (key, label) in zip(cols, ordered):
        val = metrics.get(key)
        col.metric(label, f"{val:.3f}" if isinstance(val, (int, float)) else "—")


def _plot_prediction_distribution(predictions_df: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(7, 4))
    predictions_df["qualified_probability"].hist(ax=ax, bins=12)
    ax.set_title("Prediction Probability Distribution")
    ax.set_xlabel("Qualified probability")
    ax.set_ylabel("Count")
    st.pyplot(fig)
    plt.close(fig)


def _make_zip(folder: Path) -> bytes:
    temp_zip = folder / "session_bundle.zip"
    with zipfile.ZipFile(temp_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in folder.rglob("*"):
            if path.is_file() and path.name != temp_zip.name:
                zf.write(path, path.relative_to(folder))
    data = temp_zip.read_bytes()
    temp_zip.unlink(missing_ok=True)
    return data


def _dsl_value(value: str) -> str:
    value = str(value)
    return json.dumps(value)


def _clean_project_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", name)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned:
        cleaned = "AutoGeneratedProject"
    if cleaned[0].isdigit():
        cleaned = f"Project_{cleaned}"
    return cleaned


def _detect_id_column(df: pd.DataFrame) -> str:
    candidates = [c for c in df.columns if c.lower() in {"id", "lead_id", "customer_id", "case_id", "record_id"}]
    if candidates:
        return candidates[0]
    uniqueness = []
    for col in df.columns:
        ratio = df[col].nunique(dropna=False) / max(len(df), 1)
        if ratio >= 0.95:
            uniqueness.append(col)
    return uniqueness[0] if uniqueness else df.columns[0]


def _detect_target_column(df: pd.DataFrame, id_col: str) -> str:
    priority = [c for c in df.columns if c.lower() in {"label", "target", "class", "qualified", "outcome", "y"}]
    if priority:
        return priority[0]
    binary_like = []
    for col in df.columns:
        if col == id_col:
            continue
        unique_count = df[col].dropna().nunique()
        if 2 <= unique_count <= 10:
            binary_like.append(col)
    return binary_like[-1] if binary_like else df.columns[-1]


def _infer_feature_groups(df: pd.DataFrame, id_col: str, target_col: str):
    features = [c for c in df.columns if c not in {id_col, target_col}]
    numeric, categorical = [], []
    for col in features:
        if pd.api.types.is_numeric_dtype(df[col]):
            numeric.append(col)
        else:
            categorical.append(col)
    return numeric, categorical


def _auto_generate_dsl_from_dataset(train_df: pd.DataFrame, train_path: str = "data/train.csv", score_path: str = "data/score.csv") -> tuple[str, dict]:
    id_col = _detect_id_column(train_df)
    target_col = _detect_target_column(train_df, id_col)
    numeric, categorical = _infer_feature_groups(train_df, id_col, target_col)

    if not numeric and not categorical:
        raise ValueError("No usable feature columns were found after excluding the inferred ID and target columns.")

    algorithm = "logistic_regression" if len(numeric) >= len(categorical) else "random_forest"
    project_name = _clean_project_name(Path(train_path).stem + "_pipeline")
    description = f"Auto-generated DSL specification inferred from dataset schema with {len(numeric)} numeric and {len(categorical)} categorical features."

    numeric_line = ", ".join(_dsl_value(col) for col in numeric) if numeric else _dsl_value("__none__")
    categorical_line = ", ".join(_dsl_value(col) for col in categorical) if categorical else _dsl_value("__none__")

    dsl_text = f"""project {project_name}
description {_dsl_value(description)}
data
train {_dsl_value(train_path)}
score {_dsl_value(score_path)}
id {_dsl_value(id_col)}
target {_dsl_value(target_col)}
features
numeric {numeric_line}
categorical {categorical_line}
model
algorithm {algorithm}
test_size 0.20
random_state 42
threshold 0.50
cv_folds 5
metrics accuracy, precision, recall, f1, roc_auc
outputs
model_file "artifacts/{project_name}_model.joblib"
predictions_file "outputs/{project_name}_predictions.csv"
report_file "outputs/{project_name}_report.json"
"""
    details = {
        "id_column": id_col,
        "target_column": target_col,
        "numeric_features": numeric,
        "categorical_features": categorical,
        "recommended_algorithm": algorithm,
    }
    return dsl_text, details


st.title("LeadFlowML Studio")
st.caption("End-to-end application for DSL-driven machine learning workflows built with textX and generated into CWL assets.")

with st.sidebar:
    st.header("Inputs")
    mode = st.radio("Source mode", ["Use bundled example", "Upload my own files"], index=0)
    uploaded_dsl = st.file_uploader("DSL file (.leadflow)", type=["leadflow", "txt"])
    uploaded_train = st.file_uploader("Training CSV", type=["csv"])
    uploaded_score = st.file_uploader("Scoring CSV", type=["csv"])
    auto_generate = st.button("Auto-generate DSL from dataset", use_container_width=True)
    run_generation = st.button("Run end-to-end pipeline", type="primary", use_container_width=True)
    generate_only_cwl = st.button("Generate CWL only", use_container_width=True)

if "dsl_text" not in st.session_state:
    st.session_state.dsl_text = DEFAULT_DSL.read_text(encoding="utf-8")

if uploaded_dsl is not None:
    st.session_state.dsl_text = uploaded_dsl.getvalue().decode("utf-8")

if auto_generate:
    try:
        if mode == "Use bundled example":
            preview_df = pd.read_csv(DEFAULT_TRAIN)
            generated_dsl, schema_info = _auto_generate_dsl_from_dataset(
                preview_df,
                train_path=f"data/{DEFAULT_TRAIN.name}",
                score_path=f"data/{DEFAULT_SCORE.name}",
            )
        else:
            if uploaded_train is None:
                st.error("Upload a training CSV first so the app can infer the DSL specification.")
                st.stop()
            preview_df = pd.read_csv(uploaded_train)
            score_name = uploaded_score.name if uploaded_score is not None else "score.csv"
            generated_dsl, schema_info = _auto_generate_dsl_from_dataset(
                preview_df,
                train_path="data/train.csv",
                score_path=f"data/{score_name}",
            )
        st.session_state.dsl_text = generated_dsl
        st.success("DSL specification was generated automatically from the dataset schema.")
        st.json(schema_info)
    except Exception as exc:
        st.error(f"Automatic DSL generation failed: {exc}")

st.subheader("1) DSL specification")
dsl_text = st.text_area("Edit the DSL and rerun the workflow", value=st.session_state.dsl_text, height=420)
st.session_state.dsl_text = dsl_text

with st.expander("How the automatic DSL generation works"):
    st.write(
        "The app inspects the uploaded training dataset, detects a likely ID column, selects a likely target column, "
        "splits the remaining columns into numeric and categorical features, and then writes a valid LeadFlow DSL specification for you."
    )

if run_generation or generate_only_cwl:
    with tempfile.TemporaryDirectory() as tmpdir:
        workdir = Path(tmpdir)
        for rel in ["dsl", "workflows", "data", "outputs", "artifacts", "generated_cwl", "src"]:
            (workdir / rel).mkdir(parents=True, exist_ok=True)

        shutil.copy(DEFAULT_GRAMMAR, workdir / "dsl" / "leadflow.tx")
        for src_file in (ROOT / "src").glob("*.py"):
            shutil.copy(src_file, workdir / "src" / src_file.name)

        (workdir / "workflows" / "session.leadflow").write_text(dsl_text, encoding="utf-8")

        if mode == "Use bundled example":
            shutil.copy(DEFAULT_TRAIN, workdir / "data" / DEFAULT_TRAIN.name)
            shutil.copy(DEFAULT_SCORE, workdir / "data" / DEFAULT_SCORE.name)
        else:
            if uploaded_train is None or uploaded_score is None:
                st.error("Please upload both training and scoring CSV files.")
                st.stop()
            _write_uploaded(uploaded_train, workdir / "data" / "train.csv")
            _write_uploaded(uploaded_score, workdir / "data" / uploaded_score.name)

        try:
            cfg = parse_leadflow(workdir / "dsl" / "leadflow.tx", workdir / "workflows" / "session.leadflow")
        except Exception as exc:
            st.error(f"DSL parsing failed: {exc}")
            st.stop()

        st.subheader("2) Parsed configuration")
        st.json(cfg.as_dict())

        train_df = pd.read_csv(workdir / cfg.train_path)
        score_df = pd.read_csv(workdir / cfg.score_path)
        validation = validate_config(cfg, train_df, score_df)

        st.subheader("3) Validation report")
        st.json(validation)

        outdir = workdir / "generated_cwl"
        outdir.mkdir(exist_ok=True)

        validate_doc = dslproc.cwl_tool_validate(cfg, workdir / "src")
        train_doc = dslproc.cwl_tool_train(cfg, workdir / "src")
        score_doc = dslproc.cwl_tool_score(cfg, workdir / "src")
        workflow_doc = dslproc.cwl_workflow(cfg)

        import yaml
        for name, doc in {
            "validate_data.cwl": validate_doc,
            "train_model.cwl": train_doc,
            "score_cases.cwl": score_doc,
            "workflow.cwl": workflow_doc,
        }.items():
            with open(outdir / name, "w", encoding="utf-8") as f:
                yaml.safe_dump(doc, f, sort_keys=False)

        inputs = {
            "train_csv": {"class": "File", "path": str(workdir / cfg.train_path)},
            "score_csv": {"class": "File", "path": str(workdir / cfg.score_path)},
        }
        with open(outdir / "inputs.yml", "w", encoding="utf-8") as f:
            yaml.safe_dump(inputs, f, sort_keys=False)
        (outdir / "dsl_config.json").write_text(json.dumps(cfg.as_dict(), indent=2), encoding="utf-8")

        st.subheader("4) Generated CWL assets")
        cols = st.columns(2)
        with cols[0]:
            st.code((outdir / "workflow.cwl").read_text(encoding="utf-8"), language="yaml")
        with cols[1]:
            st.code((outdir / "inputs.yml").read_text(encoding="utf-8"), language="yaml")

        cwl_zip = _make_zip(outdir)
        st.download_button("Download generated CWL bundle", data=cwl_zip, file_name="leadflow_cwl_bundle.zip", mime="application/zip")

        if not generate_only_cwl:
            report = run_training(cfg, workdir)
            predictions = run_scoring(cfg, workdir)

            st.subheader("5) Training summary")
            _render_metric_cards(report)
            st.json(report)

            st.subheader("6) Scored cases")
            st.dataframe(predictions, use_container_width=True)
            _plot_prediction_distribution(predictions)

            st.download_button(
                "Download predictions CSV",
                data=(workdir / cfg.predictions_file).read_bytes(),
                file_name=Path(cfg.predictions_file).name,
                mime="text/csv"
            )
            st.download_button(
                "Download evaluation report",
                data=(workdir / cfg.report_file).read_bytes(),
                file_name=Path(cfg.report_file).name,
                mime="application/json"
            )

with st.expander("How to run locally"):
    st.code(
        "pip install -r requirements.txt\n"
        "streamlit run app.py",
        language="bash",
    )
